### ISSUE TITLE
DIV/0 error on server tick.

### ISSUE THREAD

**Issue by Nox13last** [mmoMinecraftDev/mmoCore#16]
**Steps taken:**
1) Log in.

**Software version:**
Craftbukkit 1.1.R4-b1846 (MC1.1) (API 1.1.R3)
mmoCore v2.2
Spout v721

**Error, generated on every tick. Leaks memory until halted or exhausted:**
2012-02-05 12:19:01 [INFO] player [_IP REDACTED_] logged in with entity id 1578 at (world] -69.84975132301932, 63.0, -127.38434207821697)
2012-02-05 12:19:03 [INFO] Reading data
2012-02-05 12:19:03 [INFO] [Spout] Successfully authenticated _player's_ Spoutcraft client. Running client version: 1096
2012-02-05 12:19:03 [SEVERE] java.lang.ArithmeticException: / by zero
2012-02-05 12:19:03 [SEVERE]    at mmo.Core.MMO.getArmor(MMO.java:114)
2012-02-05 12:19:03 [SEVERE]    at mmo.Core.gui.GenericLivingEntity.getBottomValue(GenericLivingEntity.java:189)
2012-02-05 12:19:03 [SEVERE]    at mmo.Core.gui.GenericLivingEntity.onTick(GenericLivingEntity.java:246)
2012-02-05 12:19:03 [SEVERE]    at org.getspout.spoutapi.gui.GenericScreen.onTick(GenericScreen.java:139)
2012-02-05 12:19:03 [SEVERE]    at org.getspout.spoutapi.gui.InGameScreen.onTick(InGameScreen.java:70)
2012-02-05 12:19:03 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.onTick(SpoutCraftPlayer.java:1209)
2012-02-05 12:19:03 [SEVERE]    at org.getspout.spout.ServerTickTask.run(ServerTickTask.java:40)
2012-02-05 12:19:03 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
2012-02-05 12:19:03 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:503)
2012-02-05 12:19:03 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
2012-02-05 12:19:03 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by Rycochet** [comment]
Was fixed on the dev builds last week - http://files.mmo.me.uk/dev/ - just not had the time to rb everything for the new Bukkit etc...

**Comment by Nox13last** [comment]
Confirmed. Ok, thanks. I left my server and went out for about six hours. When I returned, my PC had all-but siezed up, and _megabytes_ of puke was added to the server log. Were it not for my Android RCON plugin, the server wouldn't have been able to shut down gracefully.
