### ISSUE TITLE
NPE from mmoChat

### ISSUE THREAD

**Issue by Dockter** [mmoMinecraftDev/mmoCore#17]
See Below:

2012-02-08 14:52:08 [SEVERE] Could not pass event mmoChatEvent to mmoChat 
java.lang.NullPointerException  
at org.bukkit.craftbukkit.CraftServer.getPlayer(CraftServer.java:269)  
at mmo.Chat.Channels.onMMOChat(Channels.java:81)  
at mmo.Core.MMOListener.onCustomEvent(MMOListener.java:94)  
at org.bukkit.plugin.java.JavaPluginLoader$102.execute(JavaPluginLoader.java:984)  
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:57)  
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)  
at mmo.Chat.ChatAPI.doChat(ChatAPI.java:102)  
at mmo.Chat.MMOChat$mmoPlayerListener.onPlayerCommandPreprocess(MMOChat.java:220)  
at org.bukkit.plugin.java.JavaPluginLoader$5.execute(JavaPluginLoader.java:298)  
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:57)  
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:453)  
at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:770)  
at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)  
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)  
at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:176)  
at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)  
at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)  
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)  
at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:552)  
at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)  
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)  
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)  
at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by Xaymar** [comment]
Belongs to mmoChat. See [mmoChat #13](https://github.com/mmoMinecraftDev/mmoChat/issues/13)
