### ISSUE TITLE
SpoutPlugin update seems to kill mmo-related GUI

### ISSUE THREAD

**Issue by Fureniku** [mmoMinecraftDev/mmoCore#20]
We updated to SpoutPlugin 815 for an update that allows non-generic block shapes (to get half blocks) to be added - and it seems to break all the GUI.

Right now everything we use in mmoMC is GUI-based... I know its not a recommended build of Spout, but any chance of updating to whatever broke (providing it doesn't break old versions obviously) - My logic is that I doubt it will unbreak before a new recommended Spout build anyway :D

If not I understand - I know you're busy with Spout (maybe you already know what broke it?)

**Comment by Fureniku** [comment]
2012-02-29 20:32:21 [SEVERE] Error occurred while enabling mmoPet v0.5 (Is it up to date?): org/getspout/spoutapi/event/spout/SpoutListener
java.lang.NoClassDefFoundError: org/getspout/spoutapi/event/spout/SpoutListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:224)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:37)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at mmo.Pet.MMOPet.onEnable(MMOPet.java:41)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:380)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:237)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:220)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: org.getspout.spoutapi.event.spout.SpoutListener
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 26 more

2012-02-29 20:32:21 [SEVERE] Error occurred while enabling mmoCore v2.3 (Is it up to date?): org/getspout/spoutapi/event/spout/SpoutListener
java.lang.NoClassDefFoundError: org/getspout/spoutapi/event/spout/SpoutListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:224)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:37)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at mmo.Core.MMOCore.onEnable(MMOCore.java:107)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:380)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:237)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:220)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: org.getspout.spoutapi.event.spout.SpoutListener
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 26 more

They might help :P

**Comment by Rycochet** [comment]
Actually, that's to do with the new Bukkit events - it's on my todo list for as soon as I have time, I've got the relevant page bookmarked, and just need to update all the mmo\* plugins to use them. Coincidentally I'll also have new RBs as soon as they have new RBs too :-)

**Comment by Fureniku** [comment]
Oh ok - I'm still on the equivilant of R4 though I think? :P (I use CB++ by Afforess anyway)

**Comment by Rycochet** [comment]
I haven't updated them since R1 - had a new baby on the way (now been here for 10 days) - so not had much time for updating, let alone finishing the new Spout gui code ;-)

**Comment by Fureniku** [comment]
Oh congratulations :) Take all the time you need anyway - I was more mentioning it so you know about it. Like I said everything we use this plugin for is GUI-based, so we can live without it if needs be.

**Comment by lukespragg** [comment]
Should be fixed in the latest dev builds. http://build.spout.org/view/mmoMinecraft
