### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Naddox** [mmoMinecraftDev/mmoCore#27]
Get this error after installing. Running CB 1.3.1 R2

2012-09-02 15:41:43 [SEVERE] Could not load 'plugins/mmoCore-2.3.2.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Spout
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:222)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:565)
    at org.bukkit.Bukkit.reload(Bukkit.java:183)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:21)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:492)
    at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:488)
    at net.minecraft.server.DedicatedServer.ah(DedicatedServer.java:248)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

**Comment by Rycochet** [comment]
Top line - you need to have Spout Plugin installed to use it... If you do then you'll have to wait till I get proper internet installed here and can get back to coding...

**Comment by Naddox** [comment]
Well then you should change this in the description of the plugin
Uses Spout if available

Makes it sound like spout is optional. Should say Spout is required.

**Comment by Rycochet** [comment]
Not quite sure where it says that, as it clearly states it's a Spout plugin on here, I've not touched the bukkit pages in a long time though, so might be somewhere there... It's bad that there wasn't a proper warning there, as it should simply report that Spout is required rather than causing an exception...

**Comment by Dockter** [comment]
User clearly missing SpoutPlugin.
