### ISSUE TITLE
ATTN: Dockter Failed to load - many severe errors

### ISSUE THREAD

**Issue by gtabber1117** [mmoMinecraftDev/mmoCore#29]
This is kwrinn from the spout irc chat, as requested, here is the error.

What I have done to try to alleviate this issue: Updated to Java 7-10, switched to cb-1.4.6-r0.1, completely re-installed mmocore. Each time same results as below.

Code:

```
2012-12-30 17:44:10 [INFO] This server is running CraftBukkit version git-Bukkit-1.4.6-R0.2-b2583jnks (MC: 1.4.6) (Implementing API version 1.4.6-R0.2)
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoCore-2.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: class mmo.Core.MMOPlugin overrides final method getDataFolder.()Ljava/io/File;
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:184)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.VerifyError: class mmo.Core.MMOPlugin overrides final method getDataFolder.()Ljava/io/File;
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:173)
        ... 9 more
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoInfoTime-1.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoInfoHealth-1.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoInfo-1.42.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoInfoXP-1.3.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoInfoLevel-1.21.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoInfoOnline-1.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoInfoOxygen-1.0.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoInfoBed-1.2.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoInfoWorld-1.3.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoChat-1.9.6.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:10 [INFO] ----- Bukkit Auto Updater -----
2012-12-30 17:44:10 [INFO] It appears that you're running a Beta Build, when you've specified in bukkit.yml that you prefer to run Recommended Builds.
2012-12-30 17:44:10 [INFO] If you would like to be kept informed about new Beta Build releases, it is recommended that you change 'preferred-channel' in your bukkit.yml to 'beta'.
2012-12-30 17:44:10 [INFO] With that set, you will be told whenever a new version is available for download, so that you can always keep up to date and secure with the latest fixes.
2012-12-30 17:44:10 [INFO] If you would like to disable this warning, simply set 'suggest-channels' to false in bukkit.yml.
2012-12-30 17:44:10 [INFO] ----- ------------------- -----
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoInfoCoords-1.3.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:10 [SEVERE] Could not load 'plugins\mmoInfoGold-1.0.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:11 [SEVERE] Could not load 'plugins\mmoInfoArmor-1.0.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:11 [SEVERE] Could not load 'plugins\mmoInfoCompass-1.3.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:11 [SEVERE] Could not load 'plugins\mmoInfoFood-1.2.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2012-12-30 17:44:11 [SEVERE] Could not load 'plugins\mmoInfoTicks-1.0.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: mmoCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.<init>(CraftServer.java:217)
        at net.minecraft.server.v1_4_6.PlayerList.<init>(PlayerList.java:52)
        at net.minecraft.server.v1_4_6.DedicatedPlayerList.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_6.DedicatedServer.init(DedicatedServer.java:104)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
```

**Comment by Dockter** [comment]
Use Spigot or Libigot.  Bukkit's being retarded again and locked more parts of the class loader.

**Comment by russjr08** [comment]
Hmm, I've downloaded the latest version of Spigot and I'm still getting this issue.

Edit: Libigot does the same.

**Comment by Dockter** [comment]
What version of mmocore are you using?

**Comment by russjr08** [comment]
The latest version on BukkitDev.

**Comment by Dockter** [comment]
Make sure your using 2.51
