### ISSUE TITLE
Several severe errors

### ISSUE THREAD

**Issue by gtabber1117** [mmoMinecraftDev/mmoCore#32]
Using spigot 1.5.2-r1.1-snapshot. Spoutcraft b2039 

12:03:41 PM [severe]  Could not load 'plugins\mmoInfoOnline-1.1.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoDamage.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoInfoTime-1.2.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoInfoWorld-1.3.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoTarget-1.5.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoParty-1.8.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoInfoHealth-1.1.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoChatTitle-1.3.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoInfoTicks-1.0.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoInfo-1.6.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoInfoArmor-1.1.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoInfoGold-1.3.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoInfoCoords-1.3.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:42 PM [severe]  Could not load 'plugins\mmoInfoXP-1.3.jar' in folder 'plugins'
12:03:42 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:42 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:42 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:43 PM [severe]  Could not load 'plugins\mmoInfoFood-1.3.jar' in folder 'plugins'
12:03:43 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:43 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:43 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:43 PM [severe]  Could not load 'plugins\mmoInfoCompass-1.3.jar' in folder 'plugins'
12:03:43 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:43 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:43 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:43 PM [severe]  Could not load 'plugins\mmoPet-0.7.jar' in folder 'plugins'
12:03:43 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:43 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:43 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12:03:43 PM [severe]  Could not load 'plugins\mmoChat-1.9.6.jar' in folder 'plugins'
12:03:43 PM [javastacktrace]    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
12:03:43 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
12:03:43 PM [javastacktrace]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
12:03:43 PM [javastacktrace]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

**Comment by gtabber1117** [comment]
Nevermind. When I copied the test server plugins directory over to my actual server, it seems that the plugin became corrupted. Re installed MMOcore, everything working as it should.
